[workspace]
members = [
   "src/template/rust",
   "src/langs/rust",
   "src/solutions/2023/*/rust",
   "src/solutions/2024/*/rust",
   "src/solutions/2025/*/rust",
]

[workspace.dependencies]
aoc-core = { path = "src/langs/rust" }
